# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategori.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_kategori(object):
    def setupUi(self, kategori):
        kategori.setObjectName("kategori")
        kategori.resize(618, 371)
        self.horizontalLayoutWidget = QtWidgets.QWidget(kategori)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 601, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonInsert.setFont(font)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.labelResult = QtWidgets.QLabel(kategori)
        self.labelResult.setGeometry(QtCore.QRect(10, 330, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.widget = QtWidgets.QWidget(kategori)
        self.widget.setGeometry(QtCore.QRect(10, 10, 201, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelId = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelId.setFont(font)
        self.labelId.setObjectName("labelId")
        self.verticalLayout.addWidget(self.labelId)
        self.labelName = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.widget1 = QtWidgets.QWidget(kategori)
        self.widget1.setGeometry(QtCore.QRect(230, 10, 371, 91))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditId = QtWidgets.QLineEdit(self.widget1)
        self.lineEditId.setObjectName("lineEditId")
        self.verticalLayout_2.addWidget(self.lineEditId)
        self.lineEditName = QtWidgets.QLineEdit(self.widget1)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout_2.addWidget(self.lineEditName)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.pushButtonInsert.clicked.connect(self.insertkategori)

        self.retranslateUi(kategori)
        QtCore.QMetaObject.connectSlotsByName(kategori)

    def insertkategori(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualan"
                )
            cursor = mydb.cursor()
            idkat = self.lineEditId.text()
            namekat = self.lineEditName.text()
            sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
            val = (idkat,namekat)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Kategori BerhasilDisimpan")
            self.lineEditId.setText("")
            self.lineEditName.setText("")
        except mc.Error as e:
            self.labelResult.setText("Data Kategori Gagal Disimpan")
    def retranslateUi(self, Kategori):
        _translate = QtCore.QCoreApplication.translate
        Kategori.setWindowTitle(_translate("Kategori", "FormKategori"))
        self.pushButtonInsert.setText(_translate("Kategori", "INSERTDATA"))
        self.labelId.setText(_translate("Kategori", "ID Kategori"))
        self.labelName.setText(_translate("Kategori", "NamaKategori"))
        self.labelResult.setText(_translate("Kategori", "TextLabel"))


    def retranslateUi(self, kategori):
        _translate = QtCore.QCoreApplication.translate
        kategori.setWindowTitle(_translate("kategori", "Form"))
        self.pushButtonInsert.setText(_translate("kategori", "INSERT DATA"))
        self.labelResult.setText(_translate("kategori", "TextLabel"))
        self.labelId.setText(_translate("kategori", "ID KATEGORI :"))
        self.labelName.setText(_translate("kategori", "NAMA KATEGORI :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kategori = QtWidgets.QWidget()
    ui = Ui_kategori()
    ui.setupUi(kategori)
    kategori.show()
    sys.exit(app.exec_())
