# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_kategori(object):
    def setupUi(self, kategori):
        kategori.setObjectName("kategori")
        kategori.resize(665, 539)
        self.horizontalLayoutWidget = QtWidgets.QWidget(kategori)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 140, 621, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonInsert.setFont(font)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.labelResult = QtWidgets.QLabel(kategori)
        self.labelResult.setGeometry(QtCore.QRect(10, 230, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(kategori)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 270, 641, 194))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(kategori)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 480, 631, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLoad.setFont(font)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonLoad)
        self.widget = QtWidgets.QWidget(kategori)
        self.widget.setGeometry(QtCore.QRect(10, 10, 201, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelId = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelId.setFont(font)
        self.labelId.setObjectName("labelId")
        self.verticalLayout.addWidget(self.labelId)
        self.labelName = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.widget1 = QtWidgets.QWidget(kategori)
        self.widget1.setGeometry(QtCore.QRect(230, 10, 421, 111))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditId = QtWidgets.QLineEdit(self.widget1)
        self.lineEditId.setObjectName("lineEditId")
        self.verticalLayout_2.addWidget(self.lineEditId)
        self.lineEditName = QtWidgets.QLineEdit(self.widget1)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout_2.addWidget(self.lineEditName)
        self.pushButtonLoad =QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLoad.setFont(font)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonLoad)
        self.pushButtonInsert.clicked.connect(self.insertkategori)
        self.pushButtonLoad.clicked.connect(self.loadkategori)
        
        self.retranslateUi(kategori)
        QtCore.QMetaObject.connectSlotsByName(kategori)
    def insertkategori(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditId.text()
            namekat = self.lineEditName.text()
            sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
            val = (idkat,namekat)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelResult.setText("Data Kategori BerhasilDisimpan")
            self.lineEditId.setText("")
            self.lineEditName.setText("")
        except mc.Error as e:
             self.labelResult.setText("Data Kategori Gagal Disimpan")
    
    def loadkategori(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM kategori ORDER BY ID ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number,QTableWidgetItem(str(data)))
                    self.labelResult.setText("Data Kategori BerhasilDitampilkan")
        except mc.Error as err:
            self.labelResult.setText("Data Kategori Gagal DiLoad")
            


    def retranslateUi(self, kategori):
        _translate = QtCore.QCoreApplication.translate
        kategori.setWindowTitle(_translate("kategori", "Form"))
        self.pushButtonInsert.setText(_translate("kategori", "INSERT DATA "))
        self.labelResult.setText(_translate("kategori", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("kategori", "NO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("kategori", "NAME KATEGORI"))
        self.pushButtonLoad.setText(_translate("kategori", "LOAD DATA"))
        self.labelId.setText(_translate("kategori", " ID KATEGORI :"))
        self.labelName.setText(_translate("kategori", " NAMA KATEGORI :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kategori = QtWidgets.QWidget()
    ui = Ui_kategori()
    ui.setupUi(kategori)
    kategori.show()
    sys.exit(app.exec_())
